server:
  port: 80
#-------------------------mvc页面配置-------------------------
spring:
  mvc:
    view:
      prefix: /templates
      suffix: .html
  #thymeleaf 配置
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false #关闭缓存，便于调试